on:
  pull_request:
  push:
    branches:
      - main

name: Continuous integration

jobs:
  dusk-analysis:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  code-quality:
    name: Code quality
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: cq

  docs:
    name: Build docs
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: doc

  test:
    name: Run tests
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: test

  no-std:
    name: no_std compatibility
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: no-std
      rust_target: wasm32-unknown-unknown